### ISSUE TITLE
examples require explicit loading of patchwork

### ISSUE THREAD

**Issue by simonpcouch** [graysonwhite/gglm#1]
Looking through the source, I think it might be because you are using the actual operators (i.e. `+`, `/`) loaded with the package. I haven't tried this before, but remember reading on twitter that you might need to use `plot_layout` and friends so you can use that explicit `patchwork::` prefix (and not have to load that dependency explicitly.)

**Comment by graysonwhite** [comment]
think I resolved it :-)
